apiVersion: 1

datasources:
  # ── 1. Prometheus Datasource ──
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  # ── 2. Grafana Loki Datasource ──
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
