# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# sys.path pathprefix to prepend to sys.path prior to importing modules
prepend_sys_path = .

# max length of characters to apply to the "slug" field
truncate_slug_length = 40

# logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
